name: Build WinBtrfs

on: [push]

jobs:
  build:
    runs-on: msvc-wine

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        run: cmake --version  # Ensure CMake is available

      - name: Create Build Directory
        run: mkdir -p build/amd64

      - name: Configure CMake
        run: cmake -DCMAKE_TOOLCHAIN_FILE=msvc-amd64.cmake -DCMAKE_BUILD_TYPE=Release -S . -B build/amd64

      - name: Build
        run: cmake --build build/amd64 --parallel `nproc`

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: winbtrfs-amd64
          path: build/amd64/*.sys
